version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url-shortener-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      - MONGO_URI=mongodb://mongo:27017/advanced-url-shortener
      - REDIS_URL=redis://redis:6379
      - PORT=5000
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
